### ISSUE TITLE
Cannot build React js Application

### ISSUE THREAD

**Issue by edotappstore** [dolbyio-samples/dolbyio-web-file-presentation-service#7]
using command npm run build getting error as below

> 'NODE_ENV' is not recognized as an internal or external command,
> operable program or batch file.

![image](https://user-images.githubusercontent.com/98312418/161747642-e585ef44-f7d2-42b6-91b7-e3eb1ab8662a.png)

**Comment by FabienLavocat** [comment]
Thank you @edotappstore for reporting this issue, this is due to a cross environment (macOS / Windows) compatibility issue. I will fix the script so it works on Windows as well.

**Comment by FabienLavocat** [comment]
@edotappstore please let me know if the latest version fixes the issues you were having on Windows.

**Comment by edotappstore** [comment]
> @edotappstore please let me know if the latest version fixes the issues you were having on Windows.

Hi @FabienLavocat 

That's Great thanks for the fix. React js app is now building.

![image](https://user-images.githubusercontent.com/98312418/161894702-6ee0e6a2-f52d-4c3f-b684-d0e9c5c3e7d4.png)
