### ISSUE TITLE
Cannot join as listener or guest

### ISSUE THREAD

**Issue by edotappstore** [dolbyio-samples/dolbyio-web-file-presentation-service#9]
Hello there,

I am successfully able to run the react application and build the node server and i am also able to Start Presentation by selecting a PowerPoint presentation.

The issue is now when m trying to Join as listener using the conference name which i had created earlier.
getting the below error

![image](https://user-images.githubusercontent.com/98312418/161947419-a7e9439a-60a0-4445-92b4-505addb52c3e.png)

I have printed the header and body data below in the response .

![dolbyioError](https://user-images.githubusercontent.com/98312418/161946583-3d466ecd-0b32-40d8-b87c-48f37abe6b2b.png)

Below is the screenshot of my Conference which i started in the left and right m trying to join as listener

![DolbyioOne](https://user-images.githubusercontent.com/98312418/161947089-9ff48542-54cf-4b74-9421-3b3ec75ab3b5.png)

am I missing something?

Hope I am clear in explaining the issue.

Thank you

**Comment by FabienLavocat** [comment]
Thank you @edotappstore for reporting this issue, I just pushed a fixed in this commit: https://github.com/dolbyio-samples/dolbyio-web-file-presentation-service/commit/9f4c5f8c2fadb9376ff19393ca539c2cec56deee

**Comment by edotappstore** [comment]
Thanks @FabienLavocat its working now
